#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the sockMerchant function below.
def sockMerchant(n, ar):
    res = 0
    blacklist = [] 
    for i in range(n):
        value = ar[i]
        if value not in blacklist:
            blacklist.append(value)
            num = 0
            for j in range(n):
                if ar[j] == value:
                    num +=1
            if num % 2 == 0 :
                res += num / 2
            else:
                res += (num-1) / 2
    return int(res)
